version: "3"
networks:
  ueransim:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: 10.0.0.1/24
            gateway: 10.0.0.1
            ip_range: 10.0.0.0/16
            aux_addresses:
              amf_ip: 10.0.0.10
              blocked_address1: 10.0.0.2
              blocked_address2: 10.0.0.3
     
services:
  gnb:
     image: registry.enricodebon.com:5000/university/networking-ii-2022-2021/project:ueransim
     networks:
       - ueransim
     expose:
       - "38412/sctp"
       - "2152/udp"
     cap_add:
       - NET_ADMIN
     devices:
       - "/dev/net/tun"
     privileged: true
     stdin_open: true
     tty: true
     volumes:
       - "./startGnb.sh:/UERANSIM/startGnb.sh:ro"
       - "./custom-gnb.yaml:/UERANSIM/custom-gnb.yaml:ro"
     command: "bash startGnb.sh"
  ue:
     image: registry.enricodebon.com:5000/university/networking-ii-2022-2021/project:ueransim
     networks:
       - ueransim
     volumes:
       - "./custom-ue.yaml:/UERANSIM/custom-ue.yaml:ro"
     command: "./nr-ue -c custom-ue.yaml"
