version: "3"
networks:
  #Open5GS network
  open5gs_network:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: 10.1.0.0/24
            gateway: 10.1.0.1
  # UERANSIM network
  ueransim:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: 10.0.0.1/24
            gateway: 10.0.0.1
            ip_range: 10.0.0.0/16
            aux_addresses:
              amf_ip: 10.0.0.10
              blocked_address1: 10.0.0.2
              blocked_address2: 10.0.0.3

volumes:
  mongodb_data:
    
     
services:
  # MongoDB services for Open5GS
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.5
  
  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=10.1.0.5
    volumes:
      - "./open5gs_config/provisioning/db/run_db.sh:/tmp/run.sh"
      - "./open5gs_config/provisioning/db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.19

  webui:
    image: open5gs/open5gs-webui:latest
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://10.1.0.5/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_webui.sh"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.6
  # Open5GS services
  nrf:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - mongodb
    container_name: nrf
    hostname: nrf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_waitMongo.sh"
      - "nrf"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/nrf:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.10

  ausf:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - nrf
    container_name: ausf
    hostname: ausf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_standalone.sh"
      - "ausf"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/ausf:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.12
  
  udm:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - nrf
    container_name: udm
    hostname: udm
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_standalone.sh"
      - "udm"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/udm:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.13
  
  pcf:
      image: open5gs/ubuntu-focal-open5gs-build:latest
      depends_on:
        - mongodb
        - nrf
      container_name: pcf
      hostname: pcf
      entrypoint:
        - "/bin/sh"
        - "/etc/open5gs/run_waitMongo.sh"
        - "pcf"
      volumes:
        - "./open5gs_config/config:/etc/open5gs"
        - "./open5gs_config/log/pcf:/var/log/open5gs"
      networks:
        open5gs_network:
          ipv4_address: 10.1.0.14

  nssf:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - nrf
    container_name: nssf
    hostname: nssf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_standalone.sh"
      - "nssf"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/nssf:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.15
  
  bsf:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - mongodb
      - nrf
    container_name: bsf
    hostname: bsf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_waitMongo.sh"
      - "bsf"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/bsf:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.16

  udr:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - mongodb
      - nrf
    container_name: udr
    hostname: udr
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_waitMongo.sh"
      - "udr"
    volumes:
      - "./open5gs_config/config:/etc/open5gs"
      - "./open5gs_config/log/udr:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.17

  amf:
    image: open5gs/ubuntu-focal-open5gs-build:latest
    depends_on:
      - nrf
    container_name: amf
    hostname: amf
    entrypoint:
     - "/bin/sh"
     - "/etc/open5gs/run_standalone.sh"
     - "amf"
    ports:
     - "36412:36412"
     - "36412:36412/udp"
    expose:
     - "2123"
     - "2123/udp"
    volumes:
     - "./open5gs_config/config:/etc/open5gs"
     - "./open5gs_config/log/amf:/var/log/open5gs"
    networks:
      open5gs_network:
        ipv4_address: 10.1.0.11
      ueransim:
        ipv4_address: 10.0.0.4

  # UERANSIM services
  gnb:
    image: registry.enricodebon.com:5000/university/networking-ii-2022-2021/project:ueransim
    depends_on:
      - amf
    networks:
      - ueransim
    expose:
      - "38412/sctp"
      - "2152/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - "./startGnb.sh:/UERANSIM/startGnb.sh:ro"
      - "./custom-gnb.yaml:/UERANSIM/custom-gnb.yaml:ro"
    command: "bash startGnb.sh"
  ue:
    image: registry.enricodebon.com:5000/university/networking-ii-2022-2021/project:ueransim
    depends_on:
     - gnb
    networks:
      - ueransim
    volumes:
      - "./custom-ue.yaml:/UERANSIM/custom-ue.yaml:ro"
    command: "./nr-ue -c custom-ue.yaml"