### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/amf.log

parameter:
    no_ipv6: true
    prefer_ipv4: true

amf:
    sbi:
      - addr: 10.1.0.11
        port: 7777
    ngap:
      - addr: 10.1.0.11
      - addr: 10.0.0.4
    guami: 
      plmn_id:
        mcc: 901
        mnc: 70
      amf_id:
        region: 2
        set: 1
    tai:
      plmn_id:
        mcc: 901
        mnc: 70
      tac: 1
    plmn_support:
      plmn_id:
        mcc: 901
        mnc: 70
      s_nssai:
        - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

nrf:
    sbi:
      addr: 10.1.0.10
      port: 7777