### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/nssf.log

nssf:
    sbi:
      - addr: 10.1.0.15
        port: 7777
    nsi:
      - addr: ::1
        port: 7777
        s_nssai:
          sst: 1

nrf:
    sbi:
      addr: 10.1.0.10
      port: 7777