### For reference, see `open5gs.conf`

db_uri: mongodb://10.1.0.5/open5gs

logger:
    file: /var/log/open5gs/pcf.log
    trace: 
        app: 1
        diameter: 1

parameter:
    no_ipv6: true

pcf:
    sbi:
      - addr: 10.1.0.14
        port: 7777

nrf:
    sbi:
      - addr: 10.1.0.10
        port: 7777
