### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/sgw.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgw:
    gtpc:
      addr: 10.1.0.30
    gtpu:
      addr: 10.1.0.30
