### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/sgwc.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgwc:
    gtpc:
      addr: 10.1.0.30
    pfcp:
      addr: 10.1.0.30

sgwu:
    pfcp:
      - addr: 10.1.0.31