### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/sgwu.log

parameter:
    no_ipv6: true
    prefer_ipv4: true

sgwu:
    gtpu:
      addr: 10.1.0.24
    pfcp:
      addr: 10.1.0.24

sgwc: