### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/sgwu.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgwu:
    gtpu:
      addr: 10.1.0.31
    pfcp:
      addr: 10.1.0.31