### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/smf.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true


smf:
    sbi:
      - addr: 10.1.0.60
        port: 7777
    pfcp:
      - addr: 10.1.0.60
      - addr: ::1
    gtpc:
      - addr: 10.1.0.60
      - addr: ::1
    gtpu:
      - addr: 10.1.0.60
      - addr: ::1
    subnet:
      - addr: 45.45.0.1/16
    dns:
      - 8.8.8.8
      - 8.8.4.4
    mtu: 1400
    freeDiameter: /etc/open5gs/freeDiameter/smf.conf