### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/smf.log

parameter:
    no_ipv6: true

smf:
    sbi:
      - addr: 10.1.0.18
        port: 7777
    pfcp:
      addr: 10.1.0.18
    gtpc:
      addr: 10.1.0.18
    gtpu:
      addr: 10.1.0.18
    subnet:
      addr: 10.45.0.1/16
    dns:
      - 1.1.1.1
      - 1.0.0.1
    mtu: 1400
    freeDiameter: /etc/freeDiameter/smf.conf

nrf:
    sbi:
      addr: 10.1.0.10
      port: 7777

upf:
    pfcp:
      addr: 10.1.0.19