### For reference, see `open5gs.conf`

logger:
    file: /var/log/open5gs/upf.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

upf:
    pfcp:
      - addr: 10.1.0.40
    gtpu:
      - addr: 10.1.0.40
    subnet:
      - addr: 45.45.0.1/16